service: weardynamite-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  timeout: 29
  
  environment:
    NODE_ENV: ${self:provider.stage}

custom:
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION

plugins:
  - serverless-dotenv-plugin

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi:
          path: '*'
          method: '*'