service: weardynamite-backend

package:
  individually: false
  patterns:
    - 'dist/**'
    - 'package.json'
    - '.env'
    - '!src/**'
    - '!.build/**'

build:
  esbuild: false

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  timeout: 29
  
  httpApi:
    payload: '2.0'

  environment:
    NODE_ENV: ${self:provider.stage}
    SES_REGION: ${self:provider.region}
    SES_FROM_EMAIL: "noreply@weardynamite.com"
    USE_SQS: "true"
    BACKGROUND_QUEUE_URL: 
      Ref: WeardynamiteBackgroundTaskQueue

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:DescribeTable"
            - "dynamodb:Query"
            - "dynamodb:Scan"
            - "dynamodb:GetItem"
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: "arn:aws:s3:::*"
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
            - "ses:SendRawEmail"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "sqs:SendMessage"
            - "sqs:ReceiveMessage"
            - "sqs:DeleteMessage"
            - "sqs:GetQueueAttributes"
          Resource:
            Fn::GetAtt: [ WeardynamiteBackgroundTaskQueue, Arn ]

custom:
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION

plugins:
  - serverless-dotenv-plugin

functions:
  api:
    handler: dist/handler.handler
    events:
      - httpApi:
          path: '*'
          method: '*'

  backgroundWorker:
    handler: dist/workers/backgroundWorker.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ WeardynamiteBackgroundTaskQueue, Arn ]
          batchSize: 10

resources:
  Resources:
    WeardynamiteBackgroundTaskQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "weardynamite-background-tasks-${self:provider.stage}"
        VisibilityTimeout: 60